[package]
name = "ld50_lib_windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ld50_lib = { path = "../core" }
gms_binder = { path = "../../gms_binder" }

[lib]
crate-type = ["dylib"]